// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Sprint1TestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testHomeToLogIn() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.findElement(By.linkText("Sign Up/Login")).click();
    assertThat(driver.getTitle(), is("Signin"));
  }
  @Test
  public void testLoginToSignUp() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.id("home-user")).click();
    driver.findElement(By.linkText("Sign up")).click();
    assertThat(driver.getTitle(), is("Signin"));
  }
  @Test
  public void testHomeToContactUs() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.findElement(By.id("footer-contact-link")).click();
    assertThat(driver.getTitle(), is("Contacts - Brand"));
  }
  @Test
  public void testCarouselOneClickNext() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    assertThat(driver.findElement(By.id("promo-codes-carousel")).getText(), is("FREE SHIPPING ON ORDERS OVER $50, CODE SHIP50 AT CHECKOUT"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel-2")).getText(), is("BUY ONE, GET ONE 50% OFF HORROR TITLES DURING OCTOBER, CODE SPOOKYSZN AT CHECKOUT"));
  }
  @Test
  public void testCarouselTwoClickNext() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1296, 768));
    assertThat(driver.findElement(By.id("promo-codes-carousel")).getText(), is("FREE SHIPPING ON ORDERS OVER $50, CODE SHIP50 AT CHECKOUT"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel-2")).getText(), is("BUY ONE, GET ONE 50% OFF HORROR TITLES DURING OCTOBER, CODE SPOOKYSZN AT CHECKOUT"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel-1")).getText(), is("FREE BEE\\\'S BOOKS BOOKMARK WHEN PURCHASING 3 BOOKS OR MORE"));
  }
  @Test
  public void testCarouselTreeClickNext() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    assertThat(driver.findElement(By.id("promo-codes-carousel")).getText(), is("FREE SHIPPING ON ORDERS OVER $50, CODE SHIP50 AT CHECKOUT"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel-2")).getText(), is("BUY ONE, GET ONE 50% OFF HORROR TITLES DURING OCTOBER, CODE SPOOKYSZN AT CHECKOUT"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel-1")).getText(), is("FREE BEE\\\'S BOOKS BOOKMARK WHEN PURCHASING 3 BOOKS OR MORE"));
    driver.findElement(By.cssSelector(".carousel-control-next-icon")).click();
    assertThat(driver.findElement(By.id("promo-codes-carousel")).getText(), is("FREE SHIPPING ON ORDERS OVER $50, CODE SHIP50 AT CHECKOUT"));
  }
  @Test
  public void testContactUsError() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.id("footer-contact-link")).click();
    driver.findElement(By.id("contact-submit")).click();
    driver.switchTo().frame(0);
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("close-btn")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector("#forgot-pass-home-button > span:nth-child(2)")).click();
    assertThat(driver.getTitle(), is("Home"));
  }
  @Test
  public void testContactUsFields() {
    driver.get("https://main.dva0ia48yehl5.amplifyapp.com/");
    driver.findElement(By.id("footer-contact-link")).click();
    driver.findElement(By.id("contact-name")).click();
    driver.findElement(By.id("contact-name")).sendKeys("Test");
    driver.findElement(By.id("contact-email")).sendKeys("Test@gmail.com");
    driver.findElement(By.id("contact-message")).sendKeys("Test");
    {
      String value = driver.findElement(By.id("contact-name")).getAttribute("value");
      assertThat(value, is("Test"));
    }
    {
      String value = driver.findElement(By.id("contact-email")).getAttribute("value");
      assertThat(value, is("Test@gmail.com"));
    }
    {
      String value = driver.findElement(By.id("contact-message")).getAttribute("value");
      assertThat(value, is("Test"));
    }
    driver.findElement(By.id("contact-submit")).click();
  }
}
